{% set version = "0.5.12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mess
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MESS_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MESS/MESS_{{ version }}.tar.gz
  sha256: 41e07993e67a8aab52d9d4d07a06d654186ac8a8db9b740763ed5d481f01dcf7

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-geem
    - r-geepack
    - r-ggformula
    - r-ggplot2
    - r-glmnet
    - r-kinship2
    - r-mvtnorm
  run:
    - r-base
    - r-mass
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-geem
    - r-geepack
    - r-ggformula
    - r-ggplot2
    - r-glmnet
    - r-kinship2
    - r-mvtnorm

test:
  commands:
    - $R -e "library('MESS')"           # [unix]
    - "\"%R%\" -e \"library('MESS')\""  # [win]

about:
  home: https://github.com/ekstroem/MESS
  license: GPL-2.0-only
  summary: A mixed collection of useful and semi-useful diverse statistical functions, some of which may even be referenced in The R Primer book.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj
