travis:
  secure:
    BINSTAR_TOKEN: yGuzsEEhkgC5WODaSzLHU+6f+FwnRQIoiV+857aez4CYSPquZyEIGF1GXj66dt4EF+DfCdP+9vM9Z1Hwa0AbYfY9Pm1PpyzRlVQS1Gu33XDTpZHG01g7X4ggXY4seUJcCbcHAc/Qtqt35VFYfDPP6p2fYKIRe4l/46eJfncwU3sXSdWv7VjGxd5HcYaa+RyHXAFMhZNlCrahR5w0KtKT06SzH4ckqOIXN7FK+omawMojF8TfAoFqBZ4/6uGcj1p3mfI1pvNisAu5RGv9sJMFIVtSCLziYN73FuknRKoHvMtBmiAMhAlwoa9K6bY39mbcJlsSQgle5o4fPQiKgyWtsJnw6/ACT3MzO+A37Rpf3Hhu2/KSV/+TvXBY3pNf+UzW6zPnv2tKzDunV0FVCxF0xZJFfS1gABu//+89+AHJFFqCvCKcb1p6EIYpXr7jNgjRlpKRMUvp12Oif4Tfj/4/W2bLzKO3l0OuuACnM2PwAk3VEk05pBBl0ccjTNF/OVov+/hmrawxZlM4SNLUw0V6kuGJz2ZtArj/ocifTr5CS1EZX9qpJ0T4d32x6QD4tIfY/06asVbGV1/ZGeZ+CnvXZPS4DWvO2xpvoVXMzcv4qM4eFOT6n0yi9ger4+GrJrTweeb9i1B65xeqEnTTz8FQLjSkQFgnsanX1m5s+pt75Yg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
